- hosts: all
  gather_facts: false
  collections:
    - zpe.device_connection

  tasks:
  - name: Run commands
    run_command:
        target: "{{ inventory_hostname }}"
        username: "{{ customfields.console_username }}"
        password: "{{ customfields.console_password }}"
        target_os: "{{ customfields.target_os }}"
        cmds:
          - 'show system interface'
    register: cmds_output

  - name: Write config to file
    copy:
      content: "{{ item.stdout }}"
      dest: "~/{{ inventory_hostname }}_interfaces.log"
    with_items: "{{ cmds_output.output }}"
    when: 'item.failed == False'
    loop_control:
      label: "{{ item.cmd }}"
    delegate_to: localhost