- name: Delete Connection - No Connection exist
  zpe.network.connection:
    connection_name: "CONNECTION_TEST_CELL"
    state: 'absent'
  register: output

#- name: Check Result
#  assert:
#    that:
#      - output.change_action == 'no_action'
#      - output.changed == False
#      - output.failed == false
#      - output.message == 'No change to connection CONNECTION_TEST_CELL, update was not required'

