- name: Create Connection
  zpe.network.connection:
    connection_name: "CONNECTION_TEST_CELL"
    connection_type: 'mobile_broadband_gsm'
    ethernet_interface: 'cdc-wdm1'
    connect_automatically: 'yes'
    ipv4_mode: 'dhcp'
    ipv6_mode: 'no_ipv6_address'
    enable_data_usage_monitoring: 'yes'
    sim_1_apn_configuration: 'automatic'
    sim_1_mtu: 'auto'
    enable_second_sim_card: 'no'
  register: output

#- name: Create Connection - Check Result
#  assert:
#    that:
#      - output.change_action == 'create'
#      - output.changed == True
#      - output.failed == False
#      - output.import_result.state == 'success'

- name: Create Connection - Validation
  zpe.network.connection:
    connection_name: "CONNECTION_TEST_CELL"
    connection_type: 'mobile_broadband_gsm'
    ethernet_interface: 'cdc-wdm1'
    connect_automatically: 'yes'
    ipv4_mode: 'dhcp'
    ipv6_mode: 'no_ipv6_address'
    enable_data_usage_monitoring: 'yes'
    sim_1_apn_configuration: 'automatic'
    sim_1_mtu: 'auto'
    enable_second_sim_card: 'no'
  check_mode: true
  register: output

#- name: Create Connection - Validation - Check Result
#  assert:
#    that:
#      - output.change_action == 'update'
#      - output.changed == False
#      - output.failed == False