- hosts: all
  gather_facts: false
  collections:
    -  zpe.device_connection
  vars:
    NETBOX_URL: https://<URL>
    NETBOX_API_TOKEN: <API_TOKEN>

  tasks:
    - name: Get Device Facts from a Managed Device
      zpe.device_connection.run_command:
        target: "{{ item.value.label }}"
        username: "{{ console_username }}"
        password: "{{ console_password }}"
        target_os: "{{ ansible_network_os }}"
        cmds:
          - 'execute ping 8.8.8.8'
          - 'execute ping zpecloud.com'
          - 'execute traceroute zpecloud.com'
          - 'show system interface'
          - 'get system status'
          - 'get system performance status'
      delegate_to: "{{ item.value.device.display }}"
      loop: '{{ query("netbox.netbox.nb_lookup",
                      "console-server-ports",
                      api_filter="label=<inventory_hostname>",
                      api_endpoint="https://<URL>",
                      token="<API_TOKEN>",
                      validate_certs=false) }}'
      loop_control:
        label: "{{ item.value.device.display }} - {{ item.value.name }}"
      when: inventory_hostname == item.value.label
      register: backup

    - name: Output
      debug:
        var: backup.results