- name: Delete Connection
  include: test_delete_vlan_connection_no_change.yml

- name: Create Connection
  include: test_create_vlan_connection.yml

- name: Update Connection
  include: test_update_vlan_connection.yml

- name: Delete Connection
  include: test_delete_vlan_connection.yml