- name: Create Connection
  zpe.network.connection:
    connection_name: "CONNECTION_TEST_VLAN"
    connection_type: 'vlan'
    ethernet_interface: 'eth0'
    connect_automatically: 'yes'
    ipv4_mode: 'dhcp'
    vlan_id: '105'
  register: output

#- name: Create Connection - Check Result
#  assert:
#    that:
#      - output.change_action == 'create'
#      - output.changed == True
#      - output.failed == False
#      - output.import_result.state == 'success'

- name: Create Connection - Validation
  zpe.network.connection:
    connection_name: "CONNECTION_TEST_VLAN"
    connection_type: 'vlan'
    ethernet_interface: 'eth0'
    connect_automatically: 'yes'
    ipv4_mode: 'dhcp'
    vlan_id: '105'
  check_mode: yes
  register: output

#- name: Create Connection - Validation - Check Result
#  assert:
#    that:
#      - output.change_action == 'update'
#      - output.changed == False
#      - output.failed == False