- hosts: all
  gather_facts: false
  collections:
    - zpe.device_connection

  tasks:
  - name: Get Device Facts from a Managed Device
    fact:
        target: "{{ target }}"
        username: "{{ username }}"
        password: "{{ password }}"
        target_os: "{{ target_os }}"

  - name: show Ansible_facts
    debug:
      var: ansible_facts
