- hosts: all
  gather_facts: false
  collections:
    - zpe.network

  tasks:

    - name: Get Network Facts from Nodegrid
      zpe.network.facts:

    - name: Get Network Facts from Nodegrid
      zpe.system.facts:

    - name: Display ansible_facts
      debug:
        var: ansible_facts