- hosts: all
  gather_facts: false
  collections:
    - zpe.system

  tasks:
  - name: Update zpecloud.com details on Nodegrid using import_settings
    zpe.system.nodegrid_import:
       cmds:
        - "/settings/zpe_cloud enable_zpe_cloud=yes"
        - "/settings/zpe_cloud enable_remote_access=yes"
        - "/settings/zpe_cloud enable_file_protection=no"
        - "/settings/zpe_cloud enable_file_encryption=no"
