- hosts: all
  gather_facts: false
  collections:
    - zpe.system

  tasks:
  - name: Update System Preferences
    zpe.system.preferences:
        show_hostname_on_webui_header: "{{ show_hostname }}"
        idle_timeout: "{{ idle_timeout }}"
        enable_banner: "{{ enable_banner }}"
        revision_tag: "{{ revision_tag }}"