- name: Create Connection
  zpe.network.connection:
    connection_name: "CONNECTION_TEST_BRIDGE"
    connection_type: 'bridge'
    bridge_interfaces: 'dummy99'
    connect_automatically: 'yes'
    ipv4_mode: 'dhcp'
    enable_spanning_tree_protocol: 'no'
  register: output

#- name: Create Connection - Check Result
#  assert:
#    that:
#      - output.change_action == 'create'
#      - output.changed == True
#      - output.failed == False
#      - output.import_result.state == 'success'

- name: Create Connection - Validation
  zpe.network.connection:
    connection_name: "CONNECTION_TEST_BRIDGE"
    connection_type: 'bridge'
    bridge_interfaces: 'dummy99'
    connect_automatically: 'yes'
    ipv4_mode: 'dhcp'
    enable_spanning_tree_protocol: 'no'
  check_mode: yes
  register: output

- name: Display output
  debug:
    var: output

#- name: Create Connection - Validation - Check Result
#  assert:
#    that:
#      - output.change_action == 'update'
#      - output.changed == False
#      - output.failed == False