---
plugin: netbox.netbox.nb_inventory
api_endpoint: https://<URL>
validate_certs: false
config_context: false
interfaces: false
group_by:
 - device_roles
 - platforms
compose:
 ansible_network_os: platform.slug
query_filters:
 - site: "demo"
 - has_primary_ip: True