- hosts: all
  gather_facts: false
  collections:
    - zpe.network

  tasks:

    - name: install dependencies
      shell: 'python3 -m pip install ttp --no-index --find-links=./artefacts/installation/ttp-0.9.1-py2.py3-none-any.whl'
      connection: local

    - name: Get Network Facts from Nodegrid
      zpe.network.facts:
      register: output

    - name: Get Network Facts from Nodegrid
      zpe.system.facts:
      register: output

    - name: output
      debug:
        var: ansible_facts