- hosts: all
  gather_facts: false
  collections:
    - zpe.network

  tasks:
    - name: Get Network Facts from Nodegrid
      zpe.network.facts:

    - name: output
      debug:
        var: ansible_facts