- name: Delete Connection
  zpe.network.connection:
    connection_name: "ETH0"
    state: 'absent'
  register: output

#- name: Check Result
#  assert:
#    that:
#      - output.change_action == 'delete'
#      - output.changed == True
#      - output.failed == false
#      - output.message == 'Connection ETH0 was successfully delete'

- name: Delete Connection - No Connection exist - Validate
  zpe.network.connection:
    connection_name: "ETH0"
    state: 'absent'
  check_mode:
  register: output

#- name: Check Result
#  assert:
#    that:
#      - output.change_action == 'no_action'
#      - output.changed == False
#      - output.failed == false
#      - output.message == 'No change to connection ETH0, update was not required'
