- name: Update Connection - IPv4 static
  zpe.network.connection:
    connection_name: "ETH0"
    connection_type: 'ethernet'
    ethernet_interface: 'eth0'
    connect_automatically: 'yes'
    ipv4_mode: 'static'
    ipv4_address: '192.168.29.20'
    ipv4_bitmask: '24'
    ipv4_dns_server: '8.8.8.8'
    ipv4_gateway: '192.168.29.1'
  register: output

#- name: Update Connection - IPv4 static - Check Result
#  assert:
#    that:
#      - output.change_action == 'update'
#      - output.changed == True
#      - output.failed == False
#      - output.import_result.state == 'success'

- name: Update Connection - IPv4 static - Validation
  zpe.network.connection:
    connection_name: "ETH0"
    connection_type: 'ethernet'
    ethernet_interface: 'eth0'
    connect_automatically: 'yes'
    ipv4_mode: 'static'
    ipv4_address: '192.168.29.20'
    ipv4_bitmask: '24'
    ipv4_dns_server: '8.8.8.8'
    ipv4_gateway: '192.168.29.1'
  check_mode: True
  register: output

#- name: Update Connection - IPv4 static - Validation - Check Result
#  assert:
#    that:
#      - output.change_action == 'update'
#      - output.changed == False
#      - output.failed == False

# IPv4 static - extras

- name: Update Connection - IPv4 static - extras
  zpe.network.connection:
    connection_name: "ETH0"
    connection_type: 'ethernet'
    ethernet_interface: 'eth0'
    connect_automatically: 'yes'
    ipv4_mode: 'static'
    ipv4_address: '192.168.29.20'
    ipv4_bitmask: '24'
    ipv4_dns_server: '8.8.8.8'
    ipv4_gateway: '192.168.29.1'
    ipv4_default_route_metric: '100'
    ipv4_ignore_obtained_default_gateway: 'yes'
    ipv4_ignore_obtained_dns_server: 'yes'
    ethernet_link_mode: '1g|full'
  register: output

#- name: Update Connection - IPv4 static - extras - Check Result
#  assert:
#    that:
#      - output.change_action == 'update'
#      - output.changed == True
#      - output.failed == False
#      - output.import_result.state == 'success'

- name: Update Connection - IPv4 static - extras - Validation
  zpe.network.connection:
    connection_name: "ETH0"
    connection_type: 'ethernet'
    ethernet_interface: 'eth0'
    connect_automatically: 'yes'
    ipv4_mode: 'static'
    ipv4_address: '192.168.29.20'
    ipv4_bitmask: '24'
    ipv4_dns_server: '8.8.8.8'
    ipv4_gateway: '192.168.29.1'
    ipv4_default_route_metric: '100'
    ipv4_ignore_obtained_default_gateway: 'yes'
    ipv4_ignore_obtained_dns_server: 'yes'
    ethernet_link_mode: '1g|full'
  check_mode: True
  register: output

#- name: Update Connection - IPv4 static - extras - Validation - Check Result
#  assert:
#    that:
#      - output.change_action == 'update'
#      - output.changed == False
#      - output.failed == False

# IPv6 static

- name: Update Connection - IPv6 static
  zpe.network.connection:
    connection_name: "ETH0"
    connection_type: 'ethernet'
    ethernet_interface: 'eth0'
    connect_automatically: 'yes'
    ipv4_mode: 'no_ipv4_address'
    ipv6_mode: 'static'
    ipv6_address: '2345:0425:2CA1:0000:0000:0567:5673:0002'
    ipv6_prefix_length: '64'
    ipv6_dns_server: '2345:0425:2CA1:0000:0000:0567:5673:0003'
    ipv6_gateway: '2345:0425:2CA1:0000:0000:0567:5673:0001'
    ipv6_default_route_metric: '100'
    ipv6_ignore_obtained_default_gateway: 'yes'
    ipv6_ignore_obtained_dns_server: 'yes'
  register: output

#- name: Update Connection - IPv6 static - Check Result
#  assert:
#    that:
#      - output.change_action == 'update'
#      - output.changed == True
#      - output.failed == False
#      - output.import_result.state == 'success'

- name: Update Connection - IPv6 static - Validation
  zpe.network.connection:
    connection_name: "ETH0"
    connection_type: 'ethernet'
    ethernet_interface: 'eth0'
    connect_automatically: 'yes'
    ipv4_mode: 'no_ipv4_address'
    ipv6_mode: 'static'
    ipv6_address: '2345:0425:2CA1:0000:0000:0567:5673:0002'
    ipv6_prefix_length: '64'
    ipv6_dns_server: '2345:0425:2CA1:0000:0000:0567:5673:0003'
    ipv6_gateway: '2345:0425:2CA1:0000:0000:0567:5673:0001'
    ipv6_default_route_metric: '100'
    ipv6_ignore_obtained_default_gateway: 'yes'
    ipv6_ignore_obtained_dns_server: 'yes'
  check_mode: True
  register: output

#- name: Update Connection - IPv6 static - Validation - Check Result
#  assert:
#    that:
#      - output.change_action == 'update'
#      - output.changed == False
#      - output.failed == False