- hosts: all
  gather_facts: false
  collections:
    - zpe.system

  tasks:
    - name: Get Network Facts from Nodegrid
      zpe.system.facts:

    - name: output
      debug:
        var: ansible_facts