- hosts: all
  gather_facts: false
  collections:
    - zpe.system

  tasks:
  - name: Update System Preferences
    zpe.system.preferences:
        show_hostname_on_webui_header: "yes"
        idle_timeout: "3600"
        enable_banner: "yes"